//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace no.kxml.skjema.dibk.matrikkelregistrering
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Kode", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class KodeType
    {

        private string kodeverdiField;

        private string kodebeskrivelseField;

        /// <remarks/>
        public string kodeverdi
        {
            get
            {
                return this.kodeverdiField;
            }
            set
            {
                this.kodeverdiField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kodebeskrivelse
        {
            get
            {
                return this.kodebeskrivelseField;
            }
            set
            {
                this.kodebeskrivelseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Adresse", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class AdresseType
    {

        private string adressekodeField;

        private string adressenavnField;

        private string adressenummerField;

        private string adressebokstavField;

        private string seksjonsnummerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string adressekode
        {
            get
            {
                return this.adressekodeField;
            }
            set
            {
                this.adressekodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string adressenavn
        {
            get
            {
                return this.adressenavnField;
            }
            set
            {
                this.adressenavnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string adressenummer
        {
            get
            {
                return this.adressenummerField;
            }
            set
            {
                this.adressenummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string adressebokstav
        {
            get
            {
                return this.adressebokstavField;
            }
            set
            {
                this.adressebokstavField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string seksjonsnummer
        {
            get
            {
                return this.seksjonsnummerField;
            }
            set
            {
                this.seksjonsnummerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Boligadresse", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class BoligadresseType
    {

        private string adressekodeField;

        private string adressenavnField;

        private string adressenummerField;

        private string adressebokstavField;

        private string seksjonsnummerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string adressekode
        {
            get
            {
                return this.adressekodeField;
            }
            set
            {
                this.adressekodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string adressenavn
        {
            get
            {
                return this.adressenavnField;
            }
            set
            {
                this.adressenavnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string adressenummer
        {
            get
            {
                return this.adressenummerField;
            }
            set
            {
                this.adressenummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string adressebokstav
        {
            get
            {
                return this.adressebokstavField;
            }
            set
            {
                this.adressebokstavField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string seksjonsnummer
        {
            get
            {
                return this.seksjonsnummerField;
            }
            set
            {
                this.seksjonsnummerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Bruksenhet", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class BruksenhetType
    {

        private BruksenhetsnummerType bruksenhetsnummerField;

        private System.Nullable<double> bruksarealField;

        private bool bruksarealFieldSpecified;

        private KodeType kjoekkentilgangField;

        private string antallRomField;

        private string antallBadField;

        private string antallWCField;

        private KodeType bruksenhetstypeField;

        private BoligadresseType adresseField;

        private BygningsOpplysningType boligOpplysningField;

        /// <remarks/>
        public BruksenhetsnummerType bruksenhetsnummer
        {
            get
            {
                return this.bruksenhetsnummerField;
            }
            set
            {
                this.bruksenhetsnummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<double> bruksareal
        {
            get
            {
                return this.bruksarealField;
            }
            set
            {
                this.bruksarealField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealSpecified
        {
            get
            {
                return this.bruksarealFieldSpecified;
            }
            set
            {
                this.bruksarealFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public KodeType kjoekkentilgang
        {
            get
            {
                return this.kjoekkentilgangField;
            }
            set
            {
                this.kjoekkentilgangField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", IsNullable = true)]
        public string antallRom
        {
            get
            {
                return this.antallRomField;
            }
            set
            {
                this.antallRomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", IsNullable = true)]
        public string antallBad
        {
            get
            {
                return this.antallBadField;
            }
            set
            {
                this.antallBadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", IsNullable = true)]
        public string antallWC
        {
            get
            {
                return this.antallWCField;
            }
            set
            {
                this.antallWCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public KodeType bruksenhetstype
        {
            get
            {
                return this.bruksenhetstypeField;
            }
            set
            {
                this.bruksenhetstypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public BoligadresseType adresse
        {
            get
            {
                return this.adresseField;
            }
            set
            {
                this.adresseField = value;
            }
        }

        /// <remarks/>
        public BygningsOpplysningType boligOpplysning
        {
            get
            {
                return this.boligOpplysningField;
            }
            set
            {
                this.boligOpplysningField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Bruksenhetsnummer", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class BruksenhetsnummerType
    {

        private KodeType etasjeplanField;

        private string etasjenummerField;

        private string loepenummerField;

        /// <remarks/>
        public KodeType etasjeplan
        {
            get
            {
                return this.etasjeplanField;
            }
            set
            {
                this.etasjeplanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string etasjenummer
        {
            get
            {
                return this.etasjenummerField;
            }
            set
            {
                this.etasjenummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string loepenummer
        {
            get
            {
                return this.loepenummerField;
            }
            set
            {
                this.loepenummerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    public enum BygningsOpplysningType
    {

        /// <remarks/>
        Eksisterende,

        /// <remarks/>
        Ny,

        /// <remarks/>
        Endret,

        /// <remarks/>
        Fjernet,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Bygning", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class BygningType
    {

        private string bygningsnummerField;

        private KodeType naeringsgruppeField;

        private KodeType bygningstypeField;

        private System.Nullable<double> bebygdArealField;

        private bool bebygdArealFieldSpecified;

        private EtasjeType[] etasjerField;

        private KodeType avlopField;

        private BruksenhetType[] bruksenheterField;

        private EnergiforsyningType energiforsyningField;

        private KodeType vannforsyningField;

        private System.Nullable<bool> harHeisField;

        private bool harHeisFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string bygningsnummer
        {
            get
            {
                return this.bygningsnummerField;
            }
            set
            {
                this.bygningsnummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public KodeType naeringsgruppe
        {
            get
            {
                return this.naeringsgruppeField;
            }
            set
            {
                this.naeringsgruppeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public KodeType bygningstype
        {
            get
            {
                return this.bygningstypeField;
            }
            set
            {
                this.bygningstypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<double> bebygdAreal
        {
            get
            {
                return this.bebygdArealField;
            }
            set
            {
                this.bebygdArealField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bebygdArealSpecified
        {
            get
            {
                return this.bebygdArealFieldSpecified;
            }
            set
            {
                this.bebygdArealFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("etasje", IsNullable = false)]
        public EtasjeType[] etasjer
        {
            get
            {
                return this.etasjerField;
            }
            set
            {
                this.etasjerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public KodeType avlop
        {
            get
            {
                return this.avlopField;
            }
            set
            {
                this.avlopField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("bruksenhet", IsNullable = false)]
        public BruksenhetType[] bruksenheter
        {
            get
            {
                return this.bruksenheterField;
            }
            set
            {
                this.bruksenheterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public EnergiforsyningType energiforsyning
        {
            get
            {
                return this.energiforsyningField;
            }
            set
            {
                this.energiforsyningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public KodeType vannforsyning
        {
            get
            {
                return this.vannforsyningField;
            }
            set
            {
                this.vannforsyningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> harHeis
        {
            get
            {
                return this.harHeisField;
            }
            set
            {
                this.harHeisField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool harHeisSpecified
        {
            get
            {
                return this.harHeisFieldSpecified;
            }
            set
            {
                this.harHeisFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Etasje", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class EtasjeType
    {

        private string antallBoenheterField;

        private System.Nullable<double> bruksarealTilAnnetField;

        private bool bruksarealTilAnnetFieldSpecified;

        private System.Nullable<double> bruksarealTilBoligField;

        private bool bruksarealTilBoligFieldSpecified;

        private System.Nullable<double> bruksarealTotaltField;

        private bool bruksarealTotaltFieldSpecified;

        private string etasjenummerField;

        private KodeType etasjeplanField;

        private System.Nullable<double> bruttoarealTilBoligField;

        private bool bruttoarealTilBoligFieldSpecified;

        private System.Nullable<double> bruttoarealTilAnnetField;

        private bool bruttoarealTilAnnetFieldSpecified;

        private BygningsOpplysningType etasjeopplysningField;

        private System.Nullable<double> bruttoarealTotaltField;

        private bool bruttoarealTotaltFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", IsNullable = true)]
        public string antallBoenheter
        {
            get
            {
                return this.antallBoenheterField;
            }
            set
            {
                this.antallBoenheterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<double> bruksarealTilAnnet
        {
            get
            {
                return this.bruksarealTilAnnetField;
            }
            set
            {
                this.bruksarealTilAnnetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealTilAnnetSpecified
        {
            get
            {
                return this.bruksarealTilAnnetFieldSpecified;
            }
            set
            {
                this.bruksarealTilAnnetFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<double> bruksarealTilBolig
        {
            get
            {
                return this.bruksarealTilBoligField;
            }
            set
            {
                this.bruksarealTilBoligField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealTilBoligSpecified
        {
            get
            {
                return this.bruksarealTilBoligFieldSpecified;
            }
            set
            {
                this.bruksarealTilBoligFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<double> bruksarealTotalt
        {
            get
            {
                return this.bruksarealTotaltField;
            }
            set
            {
                this.bruksarealTotaltField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruksarealTotaltSpecified
        {
            get
            {
                return this.bruksarealTotaltFieldSpecified;
            }
            set
            {
                this.bruksarealTotaltFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string etasjenummer
        {
            get
            {
                return this.etasjenummerField;
            }
            set
            {
                this.etasjenummerField = value;
            }
        }

        /// <remarks/>
        public KodeType etasjeplan
        {
            get
            {
                return this.etasjeplanField;
            }
            set
            {
                this.etasjeplanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<double> bruttoarealTilBolig
        {
            get
            {
                return this.bruttoarealTilBoligField;
            }
            set
            {
                this.bruttoarealTilBoligField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruttoarealTilBoligSpecified
        {
            get
            {
                return this.bruttoarealTilBoligFieldSpecified;
            }
            set
            {
                this.bruttoarealTilBoligFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<double> bruttoarealTilAnnet
        {
            get
            {
                return this.bruttoarealTilAnnetField;
            }
            set
            {
                this.bruttoarealTilAnnetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruttoarealTilAnnetSpecified
        {
            get
            {
                return this.bruttoarealTilAnnetFieldSpecified;
            }
            set
            {
                this.bruttoarealTilAnnetFieldSpecified = value;
            }
        }

        /// <remarks/>
        public BygningsOpplysningType etasjeopplysning
        {
            get
            {
                return this.etasjeopplysningField;
            }
            set
            {
                this.etasjeopplysningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<double> bruttoarealTotalt
        {
            get
            {
                return this.bruttoarealTotaltField;
            }
            set
            {
                this.bruttoarealTotaltField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bruttoarealTotaltSpecified
        {
            get
            {
                return this.bruttoarealTotaltFieldSpecified;
            }
            set
            {
                this.bruttoarealTotaltFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Energiforsyning", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class EnergiforsyningType
    {

        private KodeType[] varmefordelingField;

        private KodeType[] energiforsyningField;

        private System.Nullable<bool> relevantField;

        private bool relevantFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("varmefordeling", IsNullable = true)]
        public KodeType[] varmefordeling
        {
            get
            {
                return this.varmefordelingField;
            }
            set
            {
                this.varmefordelingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("energiforsyning", IsNullable = true)]
        public KodeType[] energiforsyning
        {
            get
            {
                return this.energiforsyningField;
            }
            set
            {
                this.energiforsyningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> relevant
        {
            get
            {
                return this.relevantField;
            }
            set
            {
                this.relevantField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool relevantSpecified
        {
            get
            {
                return this.relevantFieldSpecified;
            }
            set
            {
                this.relevantFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Matrikkelregistrering", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class MatrikkelregistreringType
    {

        private MatrikkelnummerType[] eiendomsidentifikasjonField;

        private AdresseType[] adresseField;

        private BygningType[] bygningField;

        private SignaturType signaturField;

        private string prosjektnavnField;

        private string kommunenavnField;

        private string dataFormatProviderField;

        private string dataFormatIdField;

        private string dataFormatVersionField;

        public MatrikkelregistreringType()
        {
            this.dataFormatProviderField = "SERES";
            this.dataFormatIdField = "5625";
            this.dataFormatVersionField = "42144";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("matrikkelnummer", IsNullable = false)]
        public MatrikkelnummerType[] eiendomsidentifikasjon
        {
            get
            {
                return this.eiendomsidentifikasjonField;
            }
            set
            {
                this.eiendomsidentifikasjonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("adresse", IsNullable = false)]
        public AdresseType[] adresse
        {
            get
            {
                return this.adresseField;
            }
            set
            {
                this.adresseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("bygning", IsNullable = false)]
        public BygningType[] bygning
        {
            get
            {
                return this.bygningField;
            }
            set
            {
                this.bygningField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public SignaturType signatur
        {
            get
            {
                return this.signaturField;
            }
            set
            {
                this.signaturField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string prosjektnavn
        {
            get
            {
                return this.prosjektnavnField;
            }
            set
            {
                this.prosjektnavnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kommunenavn
        {
            get
            {
                return this.kommunenavnField;
            }
            set
            {
                this.kommunenavnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatProvider
        {
            get
            {
                return this.dataFormatProviderField;
            }
            set
            {
                this.dataFormatProviderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatId
        {
            get
            {
                return this.dataFormatIdField;
            }
            set
            {
                this.dataFormatIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dataFormatVersion
        {
            get
            {
                return this.dataFormatVersionField;
            }
            set
            {
                this.dataFormatVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Matrikkelnummer", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class MatrikkelnummerType
    {

        private string kommunenummerField;

        private string gaardsnummerField;

        private string bruksnummerField;

        private string festenummerField;

        private string seksjonsnummerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string kommunenummer
        {
            get
            {
                return this.kommunenummerField;
            }
            set
            {
                this.kommunenummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", IsNullable = true)]
        public string gaardsnummer
        {
            get
            {
                return this.gaardsnummerField;
            }
            set
            {
                this.gaardsnummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", IsNullable = true)]
        public string bruksnummer
        {
            get
            {
                return this.bruksnummerField;
            }
            set
            {
                this.bruksnummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", IsNullable = true)]
        public string festenummer
        {
            get
            {
                return this.festenummerField;
            }
            set
            {
                this.festenummerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", IsNullable = true)]
        public string seksjonsnummer
        {
            get
            {
                return this.seksjonsnummerField;
            }
            set
            {
                this.seksjonsnummerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9")]
    [System.Xml.Serialization.XmlRootAttribute("Signatur", Namespace = "http://skjema.kxml.no/dibk/matrikkelregistrering/0.9", IsNullable = false)]
    public partial class SignaturType
    {

        private System.Nullable<System.DateTime> signaturdatoField;

        private bool signaturdatoFieldSpecified;

        private string signertAvField;

        private string signertPaaVegneAvField;

        private string signeringsstegField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> signaturdato
        {
            get
            {
                return this.signaturdatoField;
            }
            set
            {
                this.signaturdatoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signaturdatoSpecified
        {
            get
            {
                return this.signaturdatoFieldSpecified;
            }
            set
            {
                this.signaturdatoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string signertAv
        {
            get
            {
                return this.signertAvField;
            }
            set
            {
                this.signertAvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string signertPaaVegneAv
        {
            get
            {
                return this.signertPaaVegneAvField;
            }
            set
            {
                this.signertPaaVegneAvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string signeringssteg
        {
            get
            {
                return this.signeringsstegField;
            }
            set
            {
                this.signeringsstegField = value;
            }
        }
    }
}
